name: Build and Push Docker Image to Google Artifact Registry (GAR)

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Authenticate with Google Cloud
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '430.0.0'

    - name: Authenticate to Google Cloud
      run: echo "${{ secrets.GCR_CREDENTIALS_JSON }}" > ${{ runner.temp }}/key.json

    - name: Login to Google Cloud
      run: |
        gcloud auth activate-service-account --key-file=${{ runner.temp }}/key.json

    # Configure Docker for Google Artifact Registry
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    # Build the Docker image using the specified context
    - name: Build Docker image
      run: |
        IMAGE_NAME=us-central1-docker.pkg.dev/keen-defender-437704-h7/my-docker-repo/web-client
        TAG=${{ github.sha }}
        docker build -t $IMAGE_NAME:$TAG Frontend/WebClient/docker-prod
        echo $IMAGE_NAME:$TAG > image-details.txt  # Store image details for reference

    # Push the Docker image to Artifact Registry
    - name: Push Docker image
      run: |
        IMAGE_NAME=us-central1-docker.pkg.dev/keen-defender-437704-h7/my-docker-repo/web-client
        TAG=${{ github.sha }}
        docker push $IMAGE_NAME:$TAG
